GENRES = (
    ('ALT', 'Alternative'),
    ('AMB', 'Ambient'),
    ('BLU', 'Blues'),
    ('CLA', 'Classical'),
    ('DIS', 'Disco'),
    ('EMO', 'Emo'),
    ('EXP', 'Experimental'),
    ('FOL', 'Folk'),
    ('FUN', 'Funk'),
    ('HOU', 'House'),
    ('IDT', 'Industrial'),
    ('IND', 'Indie'),
    ('MET', 'Metal'),
    ('PUN', 'Punk'),
    ('RAP', 'Rap'),
    ('REG', 'Reggae'),
    ('SKA', 'Ska'),
    ('SOT', 'Soundtrack'),
    ('SOU', 'Soul'),
    ('TEC', 'Techno'),
)
