# Generated by Django 2.1.5 on 2019-03-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cover',
            field=models.CharField(default='images/record-logo.png', max_length=200),
        ),
    ]
