# Generated by Django 2.1.5 on 2019-03-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_record_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='track title')),
                ('track_num', models.IntegerField(verbose_name='track number')),
            ],
            options={
                'ordering': ['-track_num'],
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='cover',
            field=models.CharField(default='images/record-logo.png', max_length=200, verbose_name='Cover Image URL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100, verbose_name='album name'),
        ),
        migrations.AddField(
            model_name='track',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Record'),
        ),
    ]
